In [23]:
score_pca.sort_values([0,1],ascending=False)
score_fa.sort_values([0,1],ascending=False)

0         1
119  9.902147 -1.171725
347  7.789571 -1.227622
594  7.719756 -0.937309
467  7.001088 -0.394028
195  6.716115  0.663531
..        ...       ...
320 -1.372149 -0.674138
380 -1.372149 -0.674138
41  -1.377181 -0.719084
568 -1.380536 -0.749048
20  -1.383890 -0.779012

[600 rows x 2 columns]

0         1
119  9.970864 -0.085599
347  7.876963 -0.371393
594  7.775925 -0.090418
467  7.002330  0.371305
195  6.603800  1.391508
..        ...       ...
320 -1.290508 -0.819661
380 -1.290508 -0.819661
41  -1.290612 -0.864888
568 -1.290681 -0.895039
20  -1.290750 -0.925190

[600 rows x 2 columns]

In [22]:
# 得分
score_fa = pd.DataFrame(fa.get_component_scores(st_data))

In [19]:
# 设定提取主成分的方法，‘top_n'
fa.find_comps_to_retain(method='top_n',num_keep=2)
#  通过最大方差旋转 ，method="varimax"
fa.rotate_components()
# 查看因子权重
pd.DataFrame(fa.comps['rot'])

array([0, 1], dtype=int64)

0         1
0  0.002284  0.996385
1  0.520586 -0.071056
2  0.577715  0.044221
3  0.628674  0.014582

In [18]:
# 因子分析
from fa_kit import FactorAnalysis
from fa_kit import plotting as faplot
fa = FactorAnalysis.load_data_samples(
    st_data,
    preproc_scale=True,
    preproc_demean=True
)
fa.extract_components()

In [17]:
# 计算得分
score_pca = pd.DataFrame(pca_2.fit_transform(st_data))
score_pca

0         1
0    3.642864 -0.891070
1   -1.182101 -0.040078
2   -0.182031 -0.591736
3   -1.137980 -0.709455
4   -1.086750  1.343354
..        ...       ...
595  0.097364 -0.458731
596 -0.276217 -0.901276
597  3.471155  0.049195
598 -0.123971 -0.108705
599 -1.047916  1.158486

[600 rows x 2 columns]

In [16]:
pd.DataFrame(pca_2.components_.T)

0         1
0  0.110858  0.990201
1  0.509741 -0.127367
2  0.579093 -0.019002
3  0.626519 -0.054018

In [13]:
pca_2 = PCA(n_components=2)
pca_2.fit(st_data)

PCA(n_components=2)

In [12]:
pca.explained_variance_
pca.explained_variance_ratio_

array([2.50459198, 0.98645246, 0.51028464, 0.00534871])

array([0.62510442, 0.24620209, 0.12735854, 0.00133495])

In [11]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
pca.fit(st_data)

PCA(n_components=4)

In [10]:
# 数据标准化
from sklearn import preprocessing
st_data = preprocessing.scale(data)
st_data

array([[-0.296453  ,  3.68086843,  0.85513907,  2.08171356],
       [-0.1905409 , -0.80292101, -0.59755491, -0.64747691],
       [-0.56879838,  0.31802635, -0.39579186, -0.08281681],
       ...,
       [ 0.24823778,  0.01231344,  3.2762957 ,  2.45815362],
       [-0.11488941,  0.01231344, -0.11332358, -0.08281681],
       [ 1.01988304, -0.80292101, -0.59755491, -0.64747691]])

In [8]:
data = df.iloc[:,1:]

In [4]:
df = pd.read_csv('profile_telecom.csv')
df.head()

ID  cnt_call  cnt_msg  cnt_wei  cnt_web
0  1964627        46       90       36       31
1  3107769        53        2        0        2
2  3686296        28       24        5        8
3  3961002         9        2        0        4
4  4174839       145        2        0        1

In [3]:
import matplotlib.pyplot as plt
plt.style.use('seaborn')
#设置字体为黑色
plt.rcParams['font.family']='SimHei'
#显示符号
plt.rcParams['axes.unicode_minus']= False

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")
import os
os.chdir('C:\Data\Jupyter_file\统计建模\连续变量降维')