In [37]:
score = fa.get_component_scores(st_data)
bank_fa=pd.concat([df, pd.DataFrame(score)], axis=1)
bank_fa= bank_fa.rename(columns={0: "ATM-POS", 1:"TBM", 2:"CSC"})
bank_fa

ID  CNT_TBM  CNT_ATM  CNT_POS  CNT_CSC  CNT_TOT   ATM-POS  \
0          41360       34        3        3        9       49 -0.852354   
1          52094       44       17        5       18       84 -0.333078   
2          57340      122       26       32       36      216  0.918067   
3          76885       42        3        6        1       52 -0.741847   
4          89150       20       15        2        2       39 -0.499703   
...          ...      ...      ...      ...      ...      ...       ...   
99995  875638608       24        6        2        1       33 -0.788934   
99996  875656523       79        9        2        7       97 -0.692379   
99997  875663288       44      111       57        9      221  4.555096   
99998  875670226       10        5        2        1       18 -0.821689   
99999  875674475      128       18       20        1      167  0.244870   

            TBM       CSC  
0     -0.294938  0.143935  
1     -0.244334  0.939343  
2      0.593787  2.349496  
3     -0.210507 -0.521592  
4     -0.492714 -0.367629  
...         ...       ...  
99995 -0.415017 -0.492244  
99996  0.115718  0.016816  
99997 -0.466002  0.442345  
99998 -0.548095 -0.498124  
99999  0.620304 -0.500168  

[100000 rows x 9 columns]

In [33]:
# 2.设定提取主成分的方式，建议使用“top_n”法
fa.find_comps_to_retain(method='top_n', num_keep = 3)
# 3.通过最大方差法进行因子旋转
fa.rotate_components()
#查看因子权重(旋转后的权重)
pd.DataFrame(fa.comps['rot'])

array([0, 1, 2], dtype=int64)

0         1         2
0  0.004039  0.992900  0.007811
1  0.671476 -0.090569  0.100081
2  0.741002  0.076706 -0.084707
3 -0.004504  0.007874  0.991336

In [31]:
# 因子分析   pip install fa_kit
from fa_kit import FactorAnalysis
from fa_kit import plotting as fa_plotting
fa = FactorAnalysis.load_data_samples(
    st_data,     #标准化数据
    preproc_demean=True,
    preproc_scale=True
)
fa.extract_components()

In [15]:
# 计算得分
score = pd.DataFrame(pca_3.fit_transform(st_data))
bank_pca = pd.concat([df,score],axis=1)

In [30]:
# 查看变量特征
pd.DataFrame(pca_3.components_.T)

0         1         2
0  0.303020  0.834245  0.445132
1  0.555131 -0.377566  0.135542
2  0.559520 -0.315486  0.386716
3  0.535673  0.248894 -0.796201

In [29]:
# 调整参数
pca_3 = PCA(n_components=3)
pca_3.fit(st_data)

PCA(n_components=3)

In [28]:
pca.explained_variance_
pca.explained_variance_ratio_

array([1.60786876, 1.00252275, 0.7339482 , 0.65570029])

array([0.40196317, 0.25062818, 0.18348521, 0.16392343])

In [27]:
from sklearn.decomposition import PCA
pca = PCA(n_components=4)
pca.fit(st_data)

PCA(n_components=4)

In [26]:
# 作主成分前，需要数据标准化
from sklearn import preprocessing
st_data = preprocessing.scale(data)

In [25]:
data = df.iloc[:,1:5]
data.head()

CNT_TBM  CNT_ATM  CNT_POS  CNT_CSC
0       34        3        3        9
1       44       17        5       18
2      122       26       32       36
3       42        3        6        1
4       20       15        2        2

In [4]:
df = pd.read_csv('profile_bank.csv')
df.head()

ID  CNT_TBM  CNT_ATM  CNT_POS  CNT_CSC  CNT_TOT
0  41360       34        3        3        9       49
1  52094       44       17        5       18       84
2  57340      122       26       32       36      216
3  76885       42        3        6        1       52
4  89150       20       15        2        2       39

In [3]:
import matplotlib.pyplot as plt
plt.style.use('seaborn')
#设置字体为黑色
plt.rcParams['font.family']='SimHei'
#显示符号
plt.rcParams['axes.unicode_minus']= False

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")
import os
os.chdir('C:\Data\Jupyter_file\统计建模\连续变量降维')