In [22]:
# 按得分排名
Loan_pca.sort_values('score',ascending=False)

ID    X1    X2    X3    X4    X5     score
6   7  94.0  94.0  87.5  89.5  92.0  3.960102
2   3  90.7  87.3  91.0  81.5  80.0  2.603684
5   6  85.0  79.2  80.3  84.4  76.5  1.389937
0   1  76.5  81.5  76.0  75.8  71.7  0.267437
3   4  77.5  73.6  70.9  69.8  74.8 -0.440204
4   5  85.6  68.5  70.0  62.2  76.5 -0.678219
1   2  70.6  73.0  67.6  68.1  78.5 -0.775172
7   8  84.6  66.9  68.8  64.8  66.4 -1.310850
9  10  70.0  69.2  71.7  64.9  68.9 -1.486076
8   9  57.7  60.4  57.4  60.8  65.0 -3.530640

In [21]:
#主成分得分
score = pd.DataFrame(pca_1.fit_transform(st_data))
#将主成分得分合并到原始数据
Loan_pca=pd.concat([model_data, score], axis=1)
Loan_pca= Loan_pca.rename(columns={0: "score"})

In [14]:
# 通过主成分在每个变量上的权重的大小，确定每个主成分的代表性(特征向量)
pd.DataFrame(pca_1.components_).T  #第一个主成分在每个原始变量上的原始权重

0
0  0.468814
1  0.484876
2  0.472744
3  0.461747
4  0.329259

In [13]:
pca_1.explained_variance_
pca_1.explained_variance_ratio_

array([410.50559447])

array([0.84585431])

In [12]:
#模型调整(重新拟合模型)
pca_1 = PCA(n_components=1)
pca_1.fit(st_data)

PCA(n_components=1)

In [11]:
# 单个主成分解释的方差比率
pca.explained_variance_ratio_
# 4.67909448/(4.67909448+ 0.42595504 +0.33051612 +0.0883994 + 0.03159051)

array([0.84223701, 0.07667191, 0.0594929 , 0.01591189, 0.00568629])

In [10]:
# 单个主成分解释的方差(特征值)
pca.explained_variance_    #必须大于1，因为是已经标准化后的数据
# 原始第一个主成分携带原始的4.6个变量的信息

array([4.67909448, 0.42595504, 0.33051612, 0.0883994 , 0.03159051])

In [9]:
# 4.使用sklearn的主成分分析，用于判断保留主成分的数量
from sklearn.decomposition import PCA
# 建立模型,第一次n_components参数设置大一点，建议explain_var_ratio累积大于0.85；exp_var>0.8
# n_components:保留主成分的个数，初始设置一般为变量的个数
pca = PCA(n_components=5)
pca.fit(st_data)

PCA(n_components=5)

In [8]:
# 3.做主成分之前，进行中心标准化
from sklearn import preprocessing
st_data = preprocessing.scale(data)

In [7]:
data = model_data.loc[:,'X1':]
# 2.查看相关系数矩阵，判定做变量降维的必要性
data.corr()

X1        X2        X3        X4        X5
X1  1.000000  0.726655  0.825342  0.676314  0.685563
X2  0.726655  1.000000  0.929080  0.938382  0.841413
X3  0.825342  0.929080  1.000000  0.883457  0.733482
X4  0.676314  0.938382  0.883457  1.000000  0.762563
X5  0.685563  0.841413  0.733482  0.762563  1.000000

In [5]:
import os
os.chdir('C:\Data\Jupyter_file\统计建模\连续变量降维')
#1.导入数据
model_data = pd.read_csv("Loan_aply.csv",encoding='gbk')
model_data.head()

ID    X1    X2    X3    X4    X5
0   1  76.5  81.5  76.0  75.8  71.7
1   2  70.6  73.0  67.6  68.1  78.5
2   3  90.7  87.3  91.0  81.5  80.0
3   4  77.5  73.6  70.9  69.8  74.8
4   5  85.6  68.5  70.0  62.2  76.5

In [2]:
import matplotlib.pyplot as plt
plt.style.use('seaborn')
#设置字体为黑色
plt.rcParams['font.family']='SimHei'
#显示符号
plt.rcParams['axes.unicode_minus']= False

In [ ]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")
import os
os.chdir('C:\Data\Jupyter_file\统计建模')