In [71]:
#待要推荐的用户是谁
#选定你前几个朋友
#推荐前几个商品
k=2 #前几个端口
user_id=2 #目标客户
item_id=2  #端口
cal_recommend_index(2,1,4,similar_matrix=similar_matrix,up_matrix=up_matrix)

1.3663586097888587

In [70]:
#定义函数
def cal_recommend_index(k,user_id,item_id,similar_matrix,up_matrix):
    similar_k_users=similar_matrix.loc[user_id,:].sort_values(ascending=False)[1:k+1].sort_index()
    similar_id_values=up_matrix.loc[similar_k_users.index,item_id]
    u,v=similar_k_users,similar_id_values
    above=float(u@v)
    if(v==0).all():
        return 0
    below=float(u.sum())
    return above/below

In [69]:
#计算预测的分值
#计算
u,v=similar_k_users,similar_id_values
above=float(u@v)
below=float(u.sum())
score=above/below
score

1.3522384735811626

In [68]:
#根据这前看相似用户对目标评分
similar_id_values=up_matrix.loc[similar_k_users.index,item_id]
similar_id_values

user_id
1    3.0
3    0.0
Name: 2, dtype: float64

In [67]:
#推荐步骤，明确推荐的目标，选定前几个朋友，k = 2; user_id = 2;item_id = 2(商品个数）
#找出前几个最相似的用户 k=2
#找出最相似的前K个用户
similar_k_users=similar_matrix.loc[user_id,:].sort_values(ascending=False)[1:k+1].sort_index()
similar_k_users

user_id
1    0.749269
3    0.913017
Name: 2, dtype: float64

In [61]:
#相信性矩阵
matrix_sim = pd.DataFrame(cosine_similarity(up_matrix),index=up_matrix.index,columns=up_matrix.index)
matrix_sim

user_id         1         2         3         4         5         6
user_id                                                            
1        1.000000  0.749269  0.626680  0.218282  0.300000  0.000000
2        0.749269  1.000000  0.913017  0.000000  0.000000  0.157960
3        0.626680  0.913017  1.000000  0.000000  0.000000  0.403687
4        0.218282  0.000000  0.000000  1.000000  0.970143  0.639137
5        0.300000  0.000000  0.000000  0.970143  1.000000  0.527046
6        0.000000  0.157960  0.403687  0.639137  0.527046  1.000000

In [26]:
cosine_similarity(up_matrix)

array([[1.        , 0.74926865, 0.62667956, 0.21828206, 0.3       ,
        0.        ],
       [0.74926865, 1.        , 0.91301651, 0.        , 0.        ,
        0.1579597 ],
       [0.62667956, 0.91301651, 1.        , 0.        , 0.        ,
        0.40368671],
       [0.21828206, 0.        , 0.        , 1.        , 0.9701425 ,
        0.63913749],
       [0.3       , 0.        , 0.        , 0.9701425 , 1.        ,
        0.52704628],
       [0.        , 0.1579597 , 0.40368671, 0.63913749, 0.52704628,
        1.        ]])

In [66]:
similar_matrix=pd.DataFrame(cosine_similarity(up_matrix),index=up_matrix.index,columns=up_matrix.index)
#待要推荐的用户是谁
similar_matrix

user_id         1         2         3         4         5         6
user_id                                                            
1        1.000000  0.749269  0.626680  0.218282  0.300000  0.000000
2        0.749269  1.000000  0.913017  0.000000  0.000000  0.157960
3        0.626680  0.913017  1.000000  0.000000  0.000000  0.403687
4        0.218282  0.000000  0.000000  1.000000  0.970143  0.639137
5        0.300000  0.000000  0.000000  0.970143  1.000000  0.527046
6        0.000000  0.157960  0.403687  0.639137  0.527046  1.000000

In [65]:

#转换成我们需要的那种数据结构 透视表
up_matrix=df.pivot_table(index="user_id",columns="product_id",values="score")#填充一下空值
up_matrix = up_matrix.fillna(0)
up_matrix

product_id    1    2    3    4    5    6
user_id                                 
1           4.0  3.0  0.0  0.0  5.0  0.0
2           5.0  0.0  4.0  0.0  4.0  0.0
3           4.0  0.0  5.0  3.0  4.0  0.0
4           0.0  3.0  0.0  0.0  0.0  5.0
5           0.0  4.0  0.0  0.0  0.0  4.0
6           0.0  0.0  2.0  4.0  0.0  5.0

In [11]:
df = pd.read_csv('example.txt',header=None,names=['user_id',
                                    'product_id','score'])
df.shape
df.head()

(17, 3)

user_id  product_id  score
0        1           1      4
1        1           2      3
2        1           5      5
3        2           1      5
4        2           3      4

In [58]:
#转换数据结构 ，透视表,产生用户评分矩阵
up_matrix = df.pivot_table(index='user_id',columns='product_id',
               values='score')
up_matrix

product_id    1    2    3    4    5    6
user_id                                 
1           4.0  3.0  NaN  NaN  5.0  NaN
2           5.0  NaN  4.0  NaN  4.0  NaN
3           4.0  NaN  5.0  3.0  4.0  NaN
4           NaN  3.0  NaN  NaN  NaN  5.0
5           NaN  4.0  NaN  NaN  NaN  4.0
6           NaN  NaN  2.0  4.0  NaN  5.0

In [64]:
df=pd.read_csv("example.txt",header=None,names=["user_id","product_id","score"])
df.shape
df.head()

(17, 3)

user_id  product_id  score
0        1           1      4
1        1           2      3
2        1           5      5
3        2           1      5
4        2           3      4

In [9]:
import os
os.chdir('C:\Data\Jupyter_file\机器学习')

In [8]:
from sklearn.metrics.pairwise import  cosine_similarity
cosine_similarity(u)

array([[1.        , 0.63817233],
       [0.63817233, 1.        ]])

In [7]:
#计算相似性
u = np.array([[3,4,0,3,5],[5,0,0,3,1]])
type(u)
u

numpy.ndarray

array([[3, 4, 0, 3, 5],
       [5, 0, 0, 3, 1]])

In [2]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [6]:
#全部行输出
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"